### ISSUE TITLE
Is this maintained?

### ISSUE THREAD

**Issue by wagenet** [algonauti/ember-active-storage#39]
@safeforge @algodave

**Comment by safeforge** [comment]
Hey @wagenet thank you for your question. In the last year we had no chance to perform the updates on the library, however we're sill using it on production application with ember 3.20 and rails 6.0 - Our plan is to release a new version by the next couple months following the same approach used in `ember-cable`. 
Which means to use [activestorage](https://www.npmjs.com/package/activestorage) directly and avoid custom implementation in order to perform maintenance quickly. Probably a new major version will be released and the API could be a little bit different. Let me know your thoughts.

**Comment by sinankeskin** [comment]
Hi @safeforge 

Thanks for this great addon. I'm very happy with it.

If it's ok I'd like to create a PR for update this addon. I have free time and motivation.

BTW activestorage JS library still doesn't support extra headers like JWT token etc. Still not usable for addons in my opinion.

**Comment by safeforge** [comment]
@sinankeskin thank you for your support, I think would be great to upgrade and give love to the code. Since JS library is not yet ready to support extra headers my feeling is that we can proceed with gradually upgrades, for example we can split into multiple pull request.
- Update all libraries to last version
- Migrate the code to octane
- Rewrite new version using activestorage.js

wdyt?

**Comment by sinankeskin** [comment]
Sounds great. I'll let you know.

Thank you.

**Comment by wagenet** [comment]
@safeforge For now, this library meets my needs, but your suggested plan definitely sounds like the right thing for the future! Let me know if you'd like a hand with anything.

**Comment by sinankeskin** [comment]
@safeforge PR is ready.

Thanks.
